version: '2'
services:
  redis:
    image: redis:3.0
  probe:
    build:
      context: ../../../../
      dockerfile: environment/docker/images/common/ansible/Dockerfile
    links:
      - db:db
    tty: true
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    volumes:
      - ../../configuration/ansible/probe.yml:/ansible/site.yml
  nginx:
    image: nginx
    volumes_from:
      - app-rel
    volumes:
      - ../../configuration/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php:php
    ports:
      - ${PORT}:80