version: '2'
services:
  data:
    image: busybox
    volumes:
      - ../../:/app:rw
  app:
    image: kesshin/php70:latest
    volumes_from:
      - data
    tty: true
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: php-fpm
  webserver:
    image: nginx
    links:
      - app:app
    volumes_from:
      - data
    volumes:
      - ../configuration/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8082:80
