version: '2'
services:
  redis:
    image: redis:3.0
  probe:
    build:
      context: ../../../../
      dockerfile: environment/docker/images/ansible/Dockerfile
    links:
      - db:db
    tty: true
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    volumes:
      - ../../configuration/ansible/probe.yml:/ansible/site.yml
  nginx:
    image: nginx
    volumes_from:
      - app
    volumes:
      - ../../configuration/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php:php
    ports:
      - 80:80
  composer:
    image: composer/composer
    volumes_from:
      - app
    tty: true
    entrypoint: composer install
  test:
    build:
      context: ../../../../
      dockerfile: environment/docker/images/php70/xdebug/Dockerfile
    volumes_from:
      - app
    tty: true
    working_dir: /app
    command: /app/vendor/bin/phpunit tests