version: '2'
services:
  data:
    image: busybox
    volumes:
      - ../../../src/backend:/app
  db:
    image: mysql:5.7
    env_file:
      - ../../dev.env
    ports:
      - 3322:3306
    volumes:
      - ../../../mysql_data:/var/lib/mysql
      - ../configuration/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  app:
    build:
      context: ../../../
      dockerfile: environment/docker/images/common/php70/Dockerfile
    volumes_from:
      - data
    tty: true
    links:
      - db:db
      - redis:redis
    env_file:
      - ../../dev.env
    command: php-fpm
  webserver:
    image: nginx
    volumes_from:
      - data
    volumes:
      - ../configuration/nginx/conf.d:/etc/nginx/conf.d
    links:
      - app:app
    ports:
      - 80:80
  test:
    build:
      context: ../../../
      dockerfile: environment/docker/images/common/php70/xdebug/Dockerfile
    volumes_from:
      - data
    tty: true
    working_dir: /app
    command: /app/vendor/bin/phpunit tests