version: '2'
services:
  app:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/app/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    links:
      - db:db
      - redis:redis
    volumes:
      - ../images/production/app/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../images/production/app/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
  db:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/db/Dockerfile
      args:
        - DB_ROOT_PASS=${DB_ROOT_PASS}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    volumes:
      - /var/lib/mysql
  webserver:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/webserver/Dockerfile
    links:
      - app:app
    ports:
      - ${PORT}:80