version: '2'
services:
  php:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/app/Dockerfile
    links:
      - db:db
      - redis:redis
  db:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/db/Dockerfile
    env_file:
      - ../../prod.env
    volumes:
      - /var/lib/mysql
  nginx:
    build:
      context: ../../../
      dockerfile: environment/docker/images/production/nginx/Dockerfile
    links:
      - php:php
    volumes:
      - ../configuration/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - ${PORT}:80